name: ci/gh-actions/gui

on: push
env:
  FREE_DISKSPACE: |
    sudo rm -rf /usr/local/.ghcup /usr/share/dotnet /usr/share/swift /usr/share/miniconda

jobs:
  #try cache 2
  docker-linux-static:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt -y install xvfb libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1 libxcb-shape0 libxkbcommon-x11-0
    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}

    - name: Build Docker image
      run: |
        docker build --tag monero:build-env-linux --build-arg THREADS=4 --file Dockerfile.linux .
    - name: build
      run: docker run --rm -v /home/runner/work/monero-gui/monero-gui:/monero-gui -w /monero-gui monero:build-env-linux sh -c 'make release-static -j4'
    - name: sha256sum
      run: shasum -a256 /home/runner/work/monero-gui/monero-gui/build/release/bin/monero-wallet-gui
    - name: test qml
      run: xvfb-run -a /home/runner/work/monero-gui/monero-gui/build/release/bin/monero-wallet-gui --test-qml
